# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rake-version 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rake-version".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["AlphaHydrae".freeze]
  s.date = "2018-02-05"
  s.description = "Rake tasks to manage your VERSION file. No repository management (tags, committing, pushing), no release management.".freeze
  s.email = "hydrae.alpha@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/rake-version.rb",
    "lib/rake-version/config.rb",
    "lib/rake-version/context.rb",
    "lib/rake-version/copier.rb",
    "lib/rake-version/ext.rb",
    "lib/rake-version/manager.rb",
    "lib/rake-version/tasks.rb",
    "lib/rake-version/version.rb"
  ]
  s.homepage = "https://github.com/AlphaHydrae/rake-version".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.3".freeze
  s.summary = "Simple rake tasks for version management.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>.freeze, ["> 11.1"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.4"])
      s.add_development_dependency(%q<rspec-its>.freeze, ["~> 1.2"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.14"])
      s.add_development_dependency(%q<travis-lint>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<fakefs>.freeze, ["~> 0.8"])
      s.add_development_dependency(%q<coveralls>.freeze, ["~> 0.8"])
    else
      s.add_dependency(%q<rake>.freeze, ["> 11.1"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.4"])
      s.add_dependency(%q<rspec-its>.freeze, ["~> 1.2"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.14"])
      s.add_dependency(%q<travis-lint>.freeze, ["~> 2.0"])
      s.add_dependency(%q<fakefs>.freeze, ["~> 0.8"])
      s.add_dependency(%q<coveralls>.freeze, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<rake>.freeze, ["> 11.1"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.4"])
    s.add_dependency(%q<rspec-its>.freeze, ["~> 1.2"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.14"])
    s.add_dependency(%q<travis-lint>.freeze, ["~> 2.0"])
    s.add_dependency(%q<fakefs>.freeze, ["~> 0.8"])
    s.add_dependency(%q<coveralls>.freeze, ["~> 0.8"])
  end
end

